'use strict';

module.exports = {
    clock1: '🕐', 
    clock130: '🕜',
    clock2: '🕑',
    clock230: '🕝',
    clock3: '🕒',
    clock330: '🕞',
    clock4: '🕓',
    clock430: '🕟',
    clock5: '🕔',
    clock530: '🕠',
    clock6: '🕕',
    clock630: '🕡',
    clock7: '🕖',
    clock730: '🕢',
    clock8: '🕗',
    clock830: '🕣',
    clock9: '🕘',
    clock930: '🕤',
    clock10: '🕙',
    clock1030: '🕥',
    clock11: '🕚',
    clock1130: '🕦', 
    clock12: '🕛',
    clock1230: '🕧',
    regional_indicator_a : '🇦',
    regional_indicator_b : '🇧',
    regional_indicator_c : '🇨',
    regional_indicator_d : '🇩',
    regional_indicator_e : '🇪',
    regional_indicator_f : '🇫',
    regional_indicator_g : '🇬',
    regional_indicator_h : '🇭',
    regional_indicator_i : '🇮',
    regional_indicator_j : '🇯',
    regional_indicator_k : '🇰',
    regional_indicator_l : '🇱',
    regional_indicator_m : '🇲',
    regional_indicator_n : '🇳',
    regional_indicator_o : '🇴',
    regional_indicator_p : '🇵',
    regional_indicator_q : '🇶',
    regional_indicator_r : '🇷',
    regional_indicator_s : '🇸',
    regional_indicator_t : '🇹',
    regional_indicator_u : '🇺',
    regional_indicator_v : '🇻',
    regional_indicator_w : '🇼',
    regional_indicator_x : '🇽',
    regional_indicator_y : '🇾',
    regional_indicator_z : '🇿',
};